spring:
  application:
    name: consumer-ribbon-annotation
server:
  port: 8902
  
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://admin:12345678@localhost:8761/eureka