spring:
  application:
    name: consumer-movie
server:
  port: 8900
  
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka #不需要认证的请求地址
      defaultZone: http://admin:12345678@localhost:8761/eureka